import prompts from 'prompts';
import pc from 'picocolors';
import fs from 'fs';
import path from 'path';

const LOGO = `
${pc.cyan('┌─────────────────────────────────────┐')}
${pc.cyan('│')}  ${pc.bold('askai')} - Ask Any AI from your code   ${pc.cyan('│')}
${pc.cyan('└─────────────────────────────────────┘')}
`;

interface Config {
  typescript: boolean;
  srcDir: string;
  utilsPath: string;
  componentsPath: string;
}

// ─────────────────────────────────────────────────────────────
// Templates
// ─────────────────────────────────────────────────────────────

const UTILS_TEMPLATE = `// AI Service configurations and URL builders
// Generated by @raptrx/askai

export type ServiceId =
  | 'chatgpt'
  | 'claude'
  | 'gemini'
  | 'grok'
  | 'perplexity'
  | 'deepseek'
  | 'mistral'
  | 'copilot'
  | 'kagi'
  | 'google';

export interface AiService {
  name: string;
  url: string;
  buildUrl: (prompt: string) => string;
}

export const services: Record<ServiceId, AiService> = {
  chatgpt: {
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    buildUrl: (prompt) => \`https://chat.openai.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  claude: {
    name: 'Claude',
    url: 'https://claude.ai',
    buildUrl: (prompt) => \`https://claude.ai/new?q=\${encodeURIComponent(prompt)}\`,
  },
  gemini: {
    name: 'Gemini',
    url: 'https://gemini.google.com',
    buildUrl: (prompt) => \`https://gemini.google.com/app?q=\${encodeURIComponent(prompt)}\`,
  },
  grok: {
    name: 'Grok',
    url: 'https://grok.x.ai',
    buildUrl: (prompt) => \`https://grok.x.ai/?q=\${encodeURIComponent(prompt)}\`,
  },
  perplexity: {
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    buildUrl: (prompt) => \`https://perplexity.ai/search?q=\${encodeURIComponent(prompt)}\`,
  },
  deepseek: {
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    buildUrl: (prompt) => \`https://chat.deepseek.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  mistral: {
    name: 'Mistral',
    url: 'https://chat.mistral.ai',
    buildUrl: (prompt) => \`https://chat.mistral.ai/chat?q=\${encodeURIComponent(prompt)}\`,
  },
  copilot: {
    name: 'Copilot',
    url: 'https://copilot.microsoft.com',
    buildUrl: (prompt) => \`https://copilot.microsoft.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  kagi: {
    name: 'Kagi',
    url: 'https://kagi.com',
    buildUrl: (prompt) => \`https://kagi.com/assistant?q=\${encodeURIComponent(prompt)}\`,
  },
  google: {
    name: 'Google AI Studio',
    url: 'https://aistudio.google.com',
    buildUrl: (prompt) => \`https://aistudio.google.com/app/prompts?q=\${encodeURIComponent(prompt)}\`,
  },
};

export function buildPromptUrl(service: ServiceId, goal: string, content: string): string {
  const fullPrompt = \`\${goal}\\n\\n\${content}\`;
  return services[service].buildUrl(fullPrompt);
}

export function openInAI(service: ServiceId, goal: string, content: string): void {
  const url = buildPromptUrl(service, goal, content);
  window.open(url, '_blank');
}
`;

const UTILS_TEMPLATE_JS = `// AI Service configurations and URL builders
// Generated by @raptrx/askai

export const services = {
  chatgpt: {
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    buildUrl: (prompt) => \`https://chat.openai.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  claude: {
    name: 'Claude',
    url: 'https://claude.ai',
    buildUrl: (prompt) => \`https://claude.ai/new?q=\${encodeURIComponent(prompt)}\`,
  },
  gemini: {
    name: 'Gemini',
    url: 'https://gemini.google.com',
    buildUrl: (prompt) => \`https://gemini.google.com/app?q=\${encodeURIComponent(prompt)}\`,
  },
  grok: {
    name: 'Grok',
    url: 'https://grok.x.ai',
    buildUrl: (prompt) => \`https://grok.x.ai/?q=\${encodeURIComponent(prompt)}\`,
  },
  perplexity: {
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    buildUrl: (prompt) => \`https://perplexity.ai/search?q=\${encodeURIComponent(prompt)}\`,
  },
  deepseek: {
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    buildUrl: (prompt) => \`https://chat.deepseek.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  mistral: {
    name: 'Mistral',
    url: 'https://chat.mistral.ai',
    buildUrl: (prompt) => \`https://chat.mistral.ai/chat?q=\${encodeURIComponent(prompt)}\`,
  },
  copilot: {
    name: 'Copilot',
    url: 'https://copilot.microsoft.com',
    buildUrl: (prompt) => \`https://copilot.microsoft.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  kagi: {
    name: 'Kagi',
    url: 'https://kagi.com',
    buildUrl: (prompt) => \`https://kagi.com/assistant?q=\${encodeURIComponent(prompt)}\`,
  },
  google: {
    name: 'Google AI Studio',
    url: 'https://aistudio.google.com',
    buildUrl: (prompt) => \`https://aistudio.google.com/app/prompts?q=\${encodeURIComponent(prompt)}\`,
  },
};

export function buildPromptUrl(service, goal, content) {
  const fullPrompt = \`\${goal}\\n\\n\${content}\`;
  return services[service].buildUrl(fullPrompt);
}

export function openInAI(service, goal, content) {
  const url = buildPromptUrl(service, goal, content);
  window.open(url, '_blank');
}
`;

function getButtonTemplate(config: Config): string {
  const importPath = config.utilsPath.replace(/\.(ts|js)x?$/, '');

  if (config.typescript) {
    return `'use client';

import { services, openInAI, type ServiceId } from '${importPath}';

interface AskAIButtonProps {
  service: ServiceId;
  goal: string;
  content: string;
  children?: React.ReactNode;
  className?: string;
}

export function AskAIButton({ service, goal, content, children, className }: AskAIButtonProps) {
  const serviceName = services[service]?.name || service;

  return (
    <button
      onClick={() => openInAI(service, goal, content)}
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </button>
  );
}
`;
  }

  return `'use client';

import { services, openInAI } from '${importPath}';

export function AskAIButton({ service, goal, content, children, className }) {
  const serviceName = services[service]?.name || service;

  return (
    <button
      onClick={() => openInAI(service, goal, content)}
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </button>
  );
}
`;
}

function getLinkTemplate(config: Config): string {
  const importPath = config.utilsPath.replace(/\.(ts|js)x?$/, '');

  if (config.typescript) {
    return `import { services, buildPromptUrl, type ServiceId } from '${importPath}';

interface AskAILinkProps {
  service: ServiceId;
  goal: string;
  content: string;
  children?: React.ReactNode;
  className?: string;
}

export function AskAILink({ service, goal, content, children, className }: AskAILinkProps) {
  const serviceName = services[service]?.name || service;
  const url = buildPromptUrl(service, goal, content);

  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </a>
  );
}
`;
  }

  return `import { services, buildPromptUrl } from '${importPath}';

export function AskAILink({ service, goal, content, children, className }) {
  const serviceName = services[service]?.name || service;
  const url = buildPromptUrl(service, goal, content);

  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </a>
  );
}
`;
}

function getDropdownTemplate(config: Config): string {
  const importPath = config.utilsPath.replace(/\.(ts|js)x?$/, '');

  if (config.typescript) {
    return `'use client';

import { useState } from 'react';
import { services, openInAI, type ServiceId } from '${importPath}';

interface AskAIDropdownProps {
  goal: string;
  content: string;
  services?: ServiceId[];
  className?: string;
  buttonClassName?: string;
  menuClassName?: string;
  itemClassName?: string;
}

const defaultServices: ServiceId[] = ['chatgpt', 'claude', 'gemini', 'perplexity'];

export function AskAIDropdown({
  goal,
  content,
  services: selectedServices = defaultServices,
  className,
  buttonClassName,
  menuClassName,
  itemClassName,
}: AskAIDropdownProps) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={className} style={{ position: 'relative' }}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={buttonClassName}
      >
        Ask AI ▾
      </button>
      {isOpen && (
        <div
          className={menuClassName}
          style={{ position: 'absolute', top: '100%', left: 0, zIndex: 50 }}
        >
          {selectedServices.map((id) => (
            <button
              key={id}
              onClick={() => {
                openInAI(id, goal, content);
                setIsOpen(false);
              }}
              className={itemClassName}
              style={{ display: 'block', width: '100%', textAlign: 'left' }}
            >
              {services[id]?.name || id}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
`;
  }

  return `'use client';

import { useState } from 'react';
import { services, openInAI } from '${importPath}';

const defaultServices = ['chatgpt', 'claude', 'gemini', 'perplexity'];

export function AskAIDropdown({
  goal,
  content,
  services: selectedServices = defaultServices,
  className,
  buttonClassName,
  menuClassName,
  itemClassName,
}) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={className} style={{ position: 'relative' }}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={buttonClassName}
      >
        Ask AI ▾
      </button>
      {isOpen && (
        <div
          className={menuClassName}
          style={{ position: 'absolute', top: '100%', left: 0, zIndex: 50 }}
        >
          {selectedServices.map((id) => (
            <button
              key={id}
              onClick={() => {
                openInAI(id, goal, content);
                setIsOpen(false);
              }}
              className={itemClassName}
              style={{ display: 'block', width: '100%', textAlign: 'left' }}
            >
              {services[id]?.name || id}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
`;
}

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

function getConfigPath(): string {
  return path.join(process.cwd(), 'askai.json');
}

function loadConfig(): Config | null {
  const configPath = getConfigPath();
  if (fs.existsSync(configPath)) {
    return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  }
  return null;
}

function saveConfig(config: Config): void {
  fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2));
}

function ensureDir(filePath: string): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

// ─────────────────────────────────────────────────────────────
// Commands
// ─────────────────────────────────────────────────────────────

async function init(): Promise<void> {
  console.log(LOGO);

  const existing = loadConfig();
  if (existing) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: 'askai.json already exists. Overwrite?',
      initial: false,
    });
    if (!overwrite) {
      console.log(pc.yellow('Cancelled.'));
      return;
    }
  }

  // Detect TypeScript
  const hasTS = fs.existsSync(path.join(process.cwd(), 'tsconfig.json'));

  const response = await prompts([
    {
      type: 'confirm',
      name: 'typescript',
      message: 'Would you like to use TypeScript?',
      initial: hasTS,
    },
    {
      type: 'text',
      name: 'srcDir',
      message: 'Where is your source directory?',
      initial: fs.existsSync(path.join(process.cwd(), 'src')) ? 'src' : '.',
    },
    {
      type: 'text',
      name: 'utilsPath',
      message: 'Where should we put the askai utils?',
      initial: (prev: string) =>
        prev === '.' ? './lib/askai' : `./${prev}/lib/askai`,
    },
    {
      type: 'text',
      name: 'componentsPath',
      message: 'Where should we put components?',
      initial: (_prev: string, values: { srcDir: string }) =>
        values.srcDir === '.'
          ? './components/askai'
          : `./${values.srcDir}/components/askai`,
    },
  ]);

  if (!response.utilsPath) {
    console.log(pc.yellow('Cancelled.'));
    return;
  }

  const config: Config = {
    typescript: response.typescript,
    srcDir: response.srcDir,
    utilsPath: response.utilsPath,
    componentsPath: response.componentsPath,
  };

  // Save config
  saveConfig(config);
  console.log(pc.green('✓'), 'Created askai.json');

  // Write utils
  const ext = config.typescript ? '.ts' : '.js';
  const utilsFile = config.utilsPath + ext;
  ensureDir(utilsFile);
  fs.writeFileSync(
    utilsFile,
    config.typescript ? UTILS_TEMPLATE : UTILS_TEMPLATE_JS
  );
  console.log(pc.green('✓'), `Created ${utilsFile}`);

  console.log();
  console.log(pc.cyan('Next steps:'));
  console.log(`  npx askai add button    ${pc.dim('# Add AskAIButton component')}`);
  console.log(`  npx askai add link      ${pc.dim('# Add AskAILink component')}`);
  console.log(`  npx askai add dropdown  ${pc.dim('# Add AskAIDropdown component')}`);
}

async function add(componentArg?: string): Promise<void> {
  const config = loadConfig();
  if (!config) {
    console.log(pc.red('Error:'), 'No askai.json found. Run `npx askai init` first.');
    process.exit(1);
  }

  let component = componentArg?.toLowerCase();

  if (!component) {
    const response = await prompts({
      type: 'select',
      name: 'component',
      message: 'Which component would you like to add?',
      choices: [
        { title: 'AskAIButton', value: 'button', description: 'Simple button to open AI' },
        { title: 'AskAILink', value: 'link', description: 'Anchor link to AI' },
        { title: 'AskAIDropdown', value: 'dropdown', description: 'Dropdown to pick AI service' },
      ],
    });
    component = response.component;
  }

  if (!component) {
    console.log(pc.yellow('Cancelled.'));
    return;
  }

  const ext = config.typescript ? '.tsx' : '.jsx';
  let template: string;
  let fileName: string;

  switch (component) {
    case 'button':
      template = getButtonTemplate(config);
      fileName = 'ask-ai-button' + ext;
      break;
    case 'link':
      template = getLinkTemplate(config);
      fileName = 'ask-ai-link' + ext;
      break;
    case 'dropdown':
      template = getDropdownTemplate(config);
      fileName = 'ask-ai-dropdown' + ext;
      break;
    default:
      console.log(pc.red('Unknown component:'), component);
      console.log('Available: button, link, dropdown');
      process.exit(1);
  }

  const filePath = path.join(config.componentsPath, fileName);
  ensureDir(filePath);

  if (fs.existsSync(filePath)) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: `${filePath} already exists. Overwrite?`,
      initial: false,
    });
    if (!overwrite) {
      console.log(pc.yellow('Cancelled.'));
      return;
    }
  }

  fs.writeFileSync(filePath, template);
  console.log(pc.green('✓'), `Created ${filePath}`);

  console.log();
  console.log(pc.cyan('Usage:'));
  if (component === 'button') {
    console.log(`
  import { AskAIButton } from '${config.componentsPath.replace('./', '@/')}/ask-ai-button';

  <AskAIButton
    service="chatgpt"
    goal="Explain this code"
    content={codeString}
  />
`);
  } else if (component === 'link') {
    console.log(`
  import { AskAILink } from '${config.componentsPath.replace('./', '@/')}/ask-ai-link';

  <AskAILink
    service="claude"
    goal="Review this"
    content={codeString}
  />
`);
  } else if (component === 'dropdown') {
    console.log(`
  import { AskAIDropdown } from '${config.componentsPath.replace('./', '@/')}/ask-ai-dropdown';

  <AskAIDropdown
    goal="Explain this"
    content={codeString}
    services={['chatgpt', 'claude', 'gemini']}
  />
`);
  }
}

function showHelp(): void {
  console.log(`
${pc.bold('askai')} - Add AI prompt deep-linking to your project

${pc.bold('Usage:')}
  npx askai init              Initialize askai in your project
  npx askai add [component]   Add a component to your project

${pc.bold('Components:')}
  button     AskAIButton - Button that opens AI service
  link       AskAILink - Anchor link to AI service
  dropdown   AskAIDropdown - Dropdown to select AI service

${pc.bold('Examples:')}
  npx askai init
  npx askai add button
  npx askai add dropdown
`);
}

// ─────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0];

  switch (command) {
    case 'init':
      await init();
      break;
    case 'add':
      await add(args[1]);
      break;
    case '-h':
    case '--help':
    case 'help':
    case undefined:
      showHelp();
      break;
    default:
      console.log(pc.red('Unknown command:'), command);
      showHelp();
      process.exit(1);
  }
}

main().catch((err) => {
  console.error(pc.red('Error:'), err.message);
  process.exit(1);
});
