import prompts from 'prompts';
import pc from 'picocolors';
import fs from 'fs';
import path from 'path';

const LOGO = `
  ${pc.bold(pc.cyan('askai'))} ${pc.dim('v1.0')}
  ${pc.dim('Add AI buttons to your app')}
`;

interface Config {
  typescript: boolean;
  srcDir: string;
  utilsPath: string;
  componentsPath: string;
}

const AI_SERVICES = [
  { id: 'chatgpt', name: 'ChatGPT', color: '#10a37f' },
  { id: 'claude', name: 'Claude', color: '#d97706' },
  { id: 'gemini', name: 'Gemini', color: '#8b5cf6' },
  { id: 'grok', name: 'Grok', color: '#ffffff' },
  { id: 'perplexity', name: 'Perplexity', color: '#20b8cd' },
  { id: 'deepseek', name: 'DeepSeek', color: '#0066ff' },
  { id: 'mistral', name: 'Mistral', color: '#ff7000' },
  { id: 'copilot', name: 'Copilot', color: '#0078d4' },
  { id: 'kagi', name: 'Kagi', color: '#ffb319' },
  { id: 'google', name: 'Google AI', color: '#4285f4' },
];

// ─────────────────────────────────────────────────────────────
// Templates
// ─────────────────────────────────────────────────────────────

function getUtilsTemplate(ts: boolean): string {
  if (ts) {
    return `// AI Service configurations and URL builders
// Generated by @raptrx/askai - https://github.com/aliarain/askai

export type ServiceId =
  | 'chatgpt'
  | 'claude'
  | 'gemini'
  | 'grok'
  | 'perplexity'
  | 'deepseek'
  | 'mistral'
  | 'copilot'
  | 'kagi'
  | 'google';

export interface AiService {
  name: string;
  url: string;
  buildUrl: (prompt: string) => string;
}

export const services: Record<ServiceId, AiService> = {
  chatgpt: {
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    buildUrl: (prompt) => \`https://chat.openai.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  claude: {
    name: 'Claude',
    url: 'https://claude.ai',
    buildUrl: (prompt) => \`https://claude.ai/new?q=\${encodeURIComponent(prompt)}\`,
  },
  gemini: {
    name: 'Gemini',
    url: 'https://gemini.google.com',
    buildUrl: (prompt) => \`https://gemini.google.com/app?q=\${encodeURIComponent(prompt)}\`,
  },
  grok: {
    name: 'Grok',
    url: 'https://grok.x.ai',
    buildUrl: (prompt) => \`https://grok.x.ai/?q=\${encodeURIComponent(prompt)}\`,
  },
  perplexity: {
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    buildUrl: (prompt) => \`https://perplexity.ai/search?q=\${encodeURIComponent(prompt)}\`,
  },
  deepseek: {
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    buildUrl: (prompt) => \`https://chat.deepseek.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  mistral: {
    name: 'Mistral',
    url: 'https://chat.mistral.ai',
    buildUrl: (prompt) => \`https://chat.mistral.ai/chat?q=\${encodeURIComponent(prompt)}\`,
  },
  copilot: {
    name: 'Copilot',
    url: 'https://copilot.microsoft.com',
    buildUrl: (prompt) => \`https://copilot.microsoft.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  kagi: {
    name: 'Kagi',
    url: 'https://kagi.com',
    buildUrl: (prompt) => \`https://kagi.com/assistant?q=\${encodeURIComponent(prompt)}\`,
  },
  google: {
    name: 'Google AI Studio',
    url: 'https://aistudio.google.com',
    buildUrl: (prompt) => \`https://aistudio.google.com/app/prompts?q=\${encodeURIComponent(prompt)}\`,
  },
};

export function buildPromptUrl(service: ServiceId, goal: string, content: string): string {
  const fullPrompt = \`\${goal}\\n\\n\${content}\`;
  return services[service].buildUrl(fullPrompt);
}

export function openInAI(service: ServiceId, goal: string, content: string): void {
  const url = buildPromptUrl(service, goal, content);
  window.open(url, '_blank');
}

export function getAllServices(): ServiceId[] {
  return Object.keys(services) as ServiceId[];
}
`;
  }

  return `// AI Service configurations and URL builders
// Generated by @raptrx/askai - https://github.com/aliarain/askai

export const services = {
  chatgpt: {
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    buildUrl: (prompt) => \`https://chat.openai.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  claude: {
    name: 'Claude',
    url: 'https://claude.ai',
    buildUrl: (prompt) => \`https://claude.ai/new?q=\${encodeURIComponent(prompt)}\`,
  },
  gemini: {
    name: 'Gemini',
    url: 'https://gemini.google.com',
    buildUrl: (prompt) => \`https://gemini.google.com/app?q=\${encodeURIComponent(prompt)}\`,
  },
  grok: {
    name: 'Grok',
    url: 'https://grok.x.ai',
    buildUrl: (prompt) => \`https://grok.x.ai/?q=\${encodeURIComponent(prompt)}\`,
  },
  perplexity: {
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    buildUrl: (prompt) => \`https://perplexity.ai/search?q=\${encodeURIComponent(prompt)}\`,
  },
  deepseek: {
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    buildUrl: (prompt) => \`https://chat.deepseek.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  mistral: {
    name: 'Mistral',
    url: 'https://chat.mistral.ai',
    buildUrl: (prompt) => \`https://chat.mistral.ai/chat?q=\${encodeURIComponent(prompt)}\`,
  },
  copilot: {
    name: 'Copilot',
    url: 'https://copilot.microsoft.com',
    buildUrl: (prompt) => \`https://copilot.microsoft.com/?q=\${encodeURIComponent(prompt)}\`,
  },
  kagi: {
    name: 'Kagi',
    url: 'https://kagi.com',
    buildUrl: (prompt) => \`https://kagi.com/assistant?q=\${encodeURIComponent(prompt)}\`,
  },
  google: {
    name: 'Google AI Studio',
    url: 'https://aistudio.google.com',
    buildUrl: (prompt) => \`https://aistudio.google.com/app/prompts?q=\${encodeURIComponent(prompt)}\`,
  },
};

export function buildPromptUrl(service, goal, content) {
  const fullPrompt = \`\${goal}\\n\\n\${content}\`;
  return services[service].buildUrl(fullPrompt);
}

export function openInAI(service, goal, content) {
  const url = buildPromptUrl(service, goal, content);
  window.open(url, '_blank');
}

export function getAllServices() {
  return Object.keys(services);
}
`;
}

function getButtonTemplate(config: Config): string {
  const importPath = config.utilsPath.replace(/^\.\//, '@/').replace(/\.(ts|js)x?$/, '');

  if (config.typescript) {
    return `'use client';

import { services, openInAI, type ServiceId } from '${importPath}';

interface AskAIButtonProps {
  service: ServiceId;
  goal: string;
  content: string;
  children?: React.ReactNode;
  className?: string;
}

export function AskAIButton({
  service,
  goal,
  content,
  children,
  className,
}: AskAIButtonProps) {
  const serviceName = services[service]?.name || service;

  return (
    <button
      onClick={() => openInAI(service, goal, content)}
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </button>
  );
}
`;
  }

  return `'use client';

import { services, openInAI } from '${importPath}';

export function AskAIButton({ service, goal, content, children, className }) {
  const serviceName = services[service]?.name || service;

  return (
    <button
      onClick={() => openInAI(service, goal, content)}
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </button>
  );
}
`;
}

function getLinkTemplate(config: Config): string {
  const importPath = config.utilsPath.replace(/^\.\//, '@/').replace(/\.(ts|js)x?$/, '');

  if (config.typescript) {
    return `import { services, buildPromptUrl, type ServiceId } from '${importPath}';

interface AskAILinkProps {
  service: ServiceId;
  goal: string;
  content: string;
  children?: React.ReactNode;
  className?: string;
}

export function AskAILink({
  service,
  goal,
  content,
  children,
  className,
}: AskAILinkProps) {
  const serviceName = services[service]?.name || service;
  const url = buildPromptUrl(service, goal, content);

  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </a>
  );
}
`;
  }

  return `import { services, buildPromptUrl } from '${importPath}';

export function AskAILink({ service, goal, content, children, className }) {
  const serviceName = services[service]?.name || service;
  const url = buildPromptUrl(service, goal, content);

  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className={className}
    >
      {children || \`Ask \${serviceName}\`}
    </a>
  );
}
`;
}

function getDropdownTemplate(config: Config): string {
  const importPath = config.utilsPath.replace(/^\.\//, '@/').replace(/\.(ts|js)x?$/, '');

  if (config.typescript) {
    return `'use client';

import { useState, useRef, useEffect } from 'react';
import { services, openInAI, type ServiceId } from '${importPath}';

interface AskAIDropdownProps {
  goal: string;
  content: string;
  services?: ServiceId[];
  label?: string;
  className?: string;
  buttonClassName?: string;
  menuClassName?: string;
  itemClassName?: string;
}

const defaultServices: ServiceId[] = ['chatgpt', 'claude', 'gemini', 'perplexity'];

export function AskAIDropdown({
  goal,
  content,
  services: selectedServices = defaultServices,
  label = 'Ask AI',
  className,
  buttonClassName,
  menuClassName,
  itemClassName,
}: AskAIDropdownProps) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <div ref={dropdownRef} className={className} style={{ position: 'relative', display: 'inline-block' }}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={buttonClassName}
        type="button"
      >
        {label} <span style={{ marginLeft: 4 }}>{isOpen ? '▲' : '▼'}</span>
      </button>
      {isOpen && (
        <div
          className={menuClassName}
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            marginTop: 4,
            minWidth: 150,
            background: 'white',
            border: '1px solid #e5e7eb',
            borderRadius: 8,
            boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
            zIndex: 50,
            overflow: 'hidden',
          }}
        >
          {selectedServices.map((id) => (
            <button
              key={id}
              onClick={() => {
                openInAI(id, goal, content);
                setIsOpen(false);
              }}
              className={itemClassName}
              style={{
                display: 'block',
                width: '100%',
                padding: '8px 12px',
                textAlign: 'left',
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                fontSize: 14,
              }}
              onMouseEnter={(e) => (e.currentTarget.style.background = '#f3f4f6')}
              onMouseLeave={(e) => (e.currentTarget.style.background = 'none')}
            >
              {services[id]?.name || id}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
`;
  }

  return `'use client';

import { useState, useRef, useEffect } from 'react';
import { services, openInAI } from '${importPath}';

const defaultServices = ['chatgpt', 'claude', 'gemini', 'perplexity'];

export function AskAIDropdown({
  goal,
  content,
  services: selectedServices = defaultServices,
  label = 'Ask AI',
  className,
  buttonClassName,
  menuClassName,
  itemClassName,
}) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef(null);

  useEffect(() => {
    function handleClickOutside(event) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <div ref={dropdownRef} className={className} style={{ position: 'relative', display: 'inline-block' }}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={buttonClassName}
        type="button"
      >
        {label} <span style={{ marginLeft: 4 }}>{isOpen ? '▲' : '▼'}</span>
      </button>
      {isOpen && (
        <div
          className={menuClassName}
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            marginTop: 4,
            minWidth: 150,
            background: 'white',
            border: '1px solid #e5e7eb',
            borderRadius: 8,
            boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
            zIndex: 50,
            overflow: 'hidden',
          }}
        >
          {selectedServices.map((id) => (
            <button
              key={id}
              onClick={() => {
                openInAI(id, goal, content);
                setIsOpen(false);
              }}
              className={itemClassName}
              style={{
                display: 'block',
                width: '100%',
                padding: '8px 12px',
                textAlign: 'left',
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                fontSize: 14,
              }}
              onMouseEnter={(e) => (e.currentTarget.style.background = '#f3f4f6')}
              onMouseLeave={(e) => (e.currentTarget.style.background = 'none')}
            >
              {services[id]?.name || id}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
`;
}

function getButtonBarTemplate(config: Config): string {
  const importPath = config.utilsPath.replace(/^\.\//, '@/').replace(/\.(ts|js)x?$/, '');

  if (config.typescript) {
    return `'use client';

import { services, openInAI, getAllServices, type ServiceId } from '${importPath}';

interface AskAIButtonBarProps {
  goal: string;
  content: string;
  services?: ServiceId[] | 'all';
  className?: string;
  buttonClassName?: string;
  direction?: 'row' | 'column';
  gap?: number;
}

export function AskAIButtonBar({
  goal,
  content,
  services: selectedServices = ['chatgpt', 'claude', 'gemini'],
  className,
  buttonClassName,
  direction = 'row',
  gap = 8,
}: AskAIButtonBarProps) {
  const serviceList = selectedServices === 'all' ? getAllServices() : selectedServices;

  return (
    <div
      className={className}
      style={{
        display: 'flex',
        flexDirection: direction,
        gap,
        flexWrap: 'wrap',
      }}
    >
      {serviceList.map((id) => (
        <button
          key={id}
          onClick={() => openInAI(id, goal, content)}
          className={buttonClassName}
          style={{
            padding: '8px 16px',
            borderRadius: 6,
            border: '1px solid #e5e7eb',
            background: 'white',
            cursor: 'pointer',
            fontSize: 14,
            transition: 'all 0.15s',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#f9fafb';
            e.currentTarget.style.borderColor = '#d1d5db';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = 'white';
            e.currentTarget.style.borderColor = '#e5e7eb';
          }}
        >
          {services[id]?.name || id}
        </button>
      ))}
    </div>
  );
}
`;
  }

  return `'use client';

import { services, openInAI, getAllServices } from '${importPath}';

export function AskAIButtonBar({
  goal,
  content,
  services: selectedServices = ['chatgpt', 'claude', 'gemini'],
  className,
  buttonClassName,
  direction = 'row',
  gap = 8,
}) {
  const serviceList = selectedServices === 'all' ? getAllServices() : selectedServices;

  return (
    <div
      className={className}
      style={{
        display: 'flex',
        flexDirection: direction,
        gap,
        flexWrap: 'wrap',
      }}
    >
      {serviceList.map((id) => (
        <button
          key={id}
          onClick={() => openInAI(id, goal, content)}
          className={buttonClassName}
          style={{
            padding: '8px 16px',
            borderRadius: 6,
            border: '1px solid #e5e7eb',
            background: 'white',
            cursor: 'pointer',
            fontSize: 14,
            transition: 'all 0.15s',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#f9fafb';
            e.currentTarget.style.borderColor = '#d1d5db';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = 'white';
            e.currentTarget.style.borderColor = '#e5e7eb';
          }}
        >
          {services[id]?.name || id}
        </button>
      ))}
    </div>
  );
}
`;
}

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

function getConfigPath(): string {
  return path.join(process.cwd(), 'askai.json');
}

function loadConfig(): Config | null {
  const configPath = getConfigPath();
  if (fs.existsSync(configPath)) {
    return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  }
  return null;
}

function saveConfig(config: Config): void {
  fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2));
}

function ensureDir(filePath: string): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

// ─────────────────────────────────────────────────────────────
// Commands
// ─────────────────────────────────────────────────────────────

async function init(): Promise<void> {
  console.log(LOGO);

  const existing = loadConfig();
  if (existing) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: pc.yellow('askai.json already exists.') + ' Overwrite?',
      initial: false,
    });
    if (!overwrite) {
      console.log(pc.dim('Cancelled.'));
      return;
    }
  }

  // Detect environment
  const hasTS = fs.existsSync(path.join(process.cwd(), 'tsconfig.json'));
  const hasSrc = fs.existsSync(path.join(process.cwd(), 'src'));
  const hasApp = fs.existsSync(path.join(process.cwd(), 'app'));

  const response = await prompts([
    {
      type: 'confirm',
      name: 'typescript',
      message: 'Would you like to use TypeScript?',
      initial: hasTS,
    },
    {
      type: 'text',
      name: 'utilsPath',
      message: 'Where should we create the AI utils?',
      initial: hasSrc ? './src/lib/askai' : './lib/askai',
    },
    {
      type: 'text',
      name: 'componentsPath',
      message: 'Where should we create components?',
      initial: hasSrc
        ? './src/components/askai'
        : hasApp
        ? './components/askai'
        : './components/askai',
    },
  ]);

  if (!response.utilsPath) {
    console.log(pc.dim('Cancelled.'));
    return;
  }

  const config: Config = {
    typescript: response.typescript,
    srcDir: hasSrc ? 'src' : '.',
    utilsPath: response.utilsPath,
    componentsPath: response.componentsPath,
  };

  // Save config
  saveConfig(config);
  console.log(pc.green('✓'), 'Created', pc.cyan('askai.json'));

  // Write utils
  const ext = config.typescript ? '.ts' : '.js';
  const utilsFile = config.utilsPath + ext;
  ensureDir(utilsFile);
  fs.writeFileSync(utilsFile, getUtilsTemplate(config.typescript));
  console.log(pc.green('✓'), 'Created', pc.cyan(utilsFile));

  console.log();
  console.log(pc.bold('Next steps:'));
  console.log();
  console.log(`  ${pc.cyan('npx @raptrx/askai add button')}     Add a button component`);
  console.log(`  ${pc.cyan('npx @raptrx/askai add dropdown')}   Add a dropdown component`);
  console.log(`  ${pc.cyan('npx @raptrx/askai add bar')}        Add a button bar component`);
  console.log();
}

async function add(componentArg?: string): Promise<void> {
  const config = loadConfig();
  if (!config) {
    console.log(pc.red('✗'), 'No askai.json found. Run', pc.cyan('npx @raptrx/askai init'), 'first.');
    process.exit(1);
  }

  let component = componentArg?.toLowerCase();

  const components = [
    { title: 'button', value: 'button', description: 'Single AI button' },
    { title: 'link', value: 'link', description: 'SSR-friendly anchor link' },
    { title: 'dropdown', value: 'dropdown', description: 'Dropdown menu with multiple AIs' },
    { title: 'bar', value: 'bar', description: 'Button bar with multiple AIs' },
  ];

  if (!component) {
    const response = await prompts({
      type: 'select',
      name: 'component',
      message: 'Which component would you like to add?',
      choices: components,
    });
    component = response.component;
  }

  if (!component) {
    console.log(pc.dim('Cancelled.'));
    return;
  }

  const ext = config.typescript ? '.tsx' : '.jsx';
  let template: string;
  let fileName: string;

  switch (component) {
    case 'button':
      template = getButtonTemplate(config);
      fileName = 'ask-ai-button' + ext;
      break;
    case 'link':
      template = getLinkTemplate(config);
      fileName = 'ask-ai-link' + ext;
      break;
    case 'dropdown':
      template = getDropdownTemplate(config);
      fileName = 'ask-ai-dropdown' + ext;
      break;
    case 'bar':
    case 'buttonbar':
      template = getButtonBarTemplate(config);
      fileName = 'ask-ai-button-bar' + ext;
      break;
    default:
      console.log(pc.red('✗'), 'Unknown component:', pc.yellow(component));
      console.log();
      console.log('Available components:');
      components.forEach((c) => {
        console.log(`  ${pc.cyan(c.value.padEnd(10))} ${pc.dim(c.description)}`);
      });
      process.exit(1);
  }

  const filePath = path.join(config.componentsPath, fileName);
  ensureDir(filePath);

  if (fs.existsSync(filePath)) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: pc.yellow(filePath) + ' already exists. Overwrite?',
      initial: false,
    });
    if (!overwrite) {
      console.log(pc.dim('Cancelled.'));
      return;
    }
  }

  fs.writeFileSync(filePath, template);
  console.log(pc.green('✓'), 'Created', pc.cyan(filePath));

  // Show usage
  const componentPath = config.componentsPath.replace(/^\.\//, '@/');
  console.log();
  console.log(pc.bold('Usage:'));
  console.log();

  if (component === 'button') {
    console.log(pc.dim(`  import { AskAIButton } from '${componentPath}/ask-ai-button';`));
    console.log();
    console.log(`  <AskAIButton`);
    console.log(`    service="chatgpt"`);
    console.log(`    goal="Explain this code"`);
    console.log(`    content={yourContent}`);
    console.log(`  />`);
  } else if (component === 'link') {
    console.log(pc.dim(`  import { AskAILink } from '${componentPath}/ask-ai-link';`));
    console.log();
    console.log(`  <AskAILink`);
    console.log(`    service="claude"`);
    console.log(`    goal="Review this"`);
    console.log(`    content={yourContent}`);
    console.log(`  >`);
    console.log(`    Ask Claude`);
    console.log(`  </AskAILink>`);
  } else if (component === 'dropdown') {
    console.log(pc.dim(`  import { AskAIDropdown } from '${componentPath}/ask-ai-dropdown';`));
    console.log();
    console.log(`  <AskAIDropdown`);
    console.log(`    goal="Explain this"`);
    console.log(`    content={yourContent}`);
    console.log(`    services={['chatgpt', 'claude', 'gemini']}`);
    console.log(`  />`);
  } else if (component === 'bar') {
    console.log(pc.dim(`  import { AskAIButtonBar } from '${componentPath}/ask-ai-button-bar';`));
    console.log();
    console.log(`  <AskAIButtonBar`);
    console.log(`    goal="Explain this"`);
    console.log(`    content={yourContent}`);
    console.log(`    services={['chatgpt', 'claude', 'gemini']}`);
    console.log(`  />`);
  }
  console.log();
}

function showHelp(): void {
  console.log(LOGO);
  console.log(`
${pc.bold('Usage:')}
  npx @raptrx/askai ${pc.cyan('<command>')} [options]

${pc.bold('Commands:')}
  ${pc.cyan('init')}              Initialize askai in your project
  ${pc.cyan('add')} <component>   Add a component to your project

${pc.bold('Components:')}
  ${pc.cyan('button')}    Single button to open AI service
  ${pc.cyan('link')}      Anchor link (SSR-friendly)
  ${pc.cyan('dropdown')}  Dropdown menu with multiple AI services
  ${pc.cyan('bar')}       Button bar with multiple AI services

${pc.bold('Examples:')}
  npx @raptrx/askai init
  npx @raptrx/askai add button
  npx @raptrx/askai add dropdown

${pc.bold('AI Services:')}
  ${AI_SERVICES.map((s) => s.id).join(', ')}

${pc.dim('Documentation: https://github.com/aliarain/askai')}
`);
}

// ─────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0];

  switch (command) {
    case 'init':
      await init();
      break;
    case 'add':
      await add(args[1]);
      break;
    case '-h':
    case '--help':
    case 'help':
    case undefined:
      showHelp();
      break;
    case '-v':
    case '--version':
      console.log('1.1.0');
      break;
    default:
      console.log(pc.red('✗'), 'Unknown command:', pc.yellow(command));
      console.log();
      console.log('Run', pc.cyan('npx @raptrx/askai --help'), 'for usage.');
      process.exit(1);
  }
}

main().catch((err) => {
  console.error(pc.red('Error:'), err.message);
  process.exit(1);
});
